### ISSUE TITLE
python setup.py build_ext --inplace 报错

### ISSUE THREAD

**Issue by fire2fire2** [MCG-NJU/SparseBEV#13]
感谢优秀的工作！
我按照GitHub的environment部分进行环境配置，选择的是PyTorch 1.10.2 + CUDA 10.2 for older GPUs版本，最后在Compile CUDA extensions部分报错，似乎是因PyTorch 1.10.2不兼容的原因？
Traceback (most recent call last):
  File "/opt/conda/envs/sparsebev/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1717, in _run_ninja_build
    subprocess.run(
  File "/opt/conda/envs/sparsebev/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    setup(
  File "/opt/conda/envs/sparsebev/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/conda/envs/sparsebev/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/conda/envs/sparsebev/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/conda/envs/sparsebev/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/sparsebev/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/opt/conda/envs/sparsebev/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/opt/conda/envs/sparsebev/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 735, in build_extensions
    build_ext.build_extensions(self)
  File "/opt/conda/envs/sparsebev/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/opt/conda/envs/sparsebev/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/opt/conda/envs/sparsebev/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/opt/conda/envs/sparsebev/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/opt/conda/envs/sparsebev/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 556, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/opt/conda/envs/sparsebev/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1399, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/opt/conda/envs/sparsebev/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by afterthat97** [comment]
你的error信息是不是没复制全，这些看不出源头问题

**Comment by fire2fire2** [comment]
感谢回复，刚刚解决了～

**Comment by fire2fire2** [comment]
请问r50_in1k_704x256.py这个配置用8张v100或a100大概要跑多久？

**Comment by afterthat97** [comment]
一天内吧，不过这个in1k配置不稳定，点数波动很大，推荐nuimg那个

**Comment by fire2fire2** [comment]
不好意思，还要请教一下为什么eta时间这么久呢？而且每隔8次iteration左右data loda的时间就会很久，是data读取有问题吗？已经按照GitHub的步骤完成了Install turbojpeg and pillow-simd to speed up data loading这一步的配置。
[2023-09-21 21:35:43,256][INFO] - Epoch [1/24][1850/3517] loss: 7.69, eta: 9 days, 3:17:27, time: 15.87s, data: 14995ms, mem: 1975M
[2023-09-21 21:35:51,688][INFO] - Epoch [1/24][1851/3517] loss: 7.41, eta: 9 days, 3:16:27, time: 8.44s, data: 28ms, mem: 1975M
[2023-09-21 21:35:53,010][INFO] - Epoch [1/24][1852/3517] loss: 9.81, eta: 9 days, 3:10:10, time: 1.32s, data: 24ms, mem: 1975M
[2023-09-21 21:35:58,550][INFO] - Epoch [1/24][1853/3517] loss: 6.93, eta: 9 days, 3:07:01, time: 5.54s, data: 29ms, mem: 1975M
[2023-09-21 21:36:01,934][INFO] - Epoch [1/24][1854/3517] loss: 8.57, eta: 9 days, 3:02:17, time: 3.39s, data: 33ms, mem: 1975M
[2023-09-21 21:36:40,447][INFO] - Epoch [1/24][1855/3517] loss: 7.48, eta: 9 days, 3:23:37, time: 38.51s, data: 37643ms, mem: 1975M
[2023-09-21 21:36:47,626][INFO] - Epoch [1/24][1856/3517] loss: 7.32, eta: 9 days, 3:21:42, time: 7.18s, data: 24ms, mem: 1975M
[2023-09-21 21:36:52,744][INFO] - Epoch [1/24][1857/3517] loss: 7.80, eta: 9 days, 3:18:14, time: 5.12s, data: 25ms, mem: 1975M
[2023-09-21 21:37:07,610][INFO] - Epoch [1/24][1858/3517] loss: 7.09, eta: 9 days, 3:22:00, time: 14.85s, data: 13851ms, mem: 1975M
[2023-09-21 21:37:11,196][INFO] - Epoch [1/24][1859/3517] loss: 7.41, eta: 9 days, 3:17:25, time: 3.59s, data: 33ms, mem: 1975M
[2023-09-21 21:37:16,992][INFO] - Epoch [1/24][1860/3517] loss: 6.89, eta: 9 days, 3:14:28, time: 5.79s, data: 28ms, mem: 1975M
[2023-09-21 21:37:22,258][INFO] - Epoch [1/24][1861/3517] loss: 8.25, eta: 9 days, 3:11:08, time: 5.27s, data: 32ms, mem: 1975M
[2023-09-21 21:37:26,912][INFO] - Epoch [1/24][1862/3517] loss: 6.77, eta: 9 days, 3:07:20, time: 4.65s, data: 24ms, mem: 1975M
[2023-09-21 21:38:07,257][INFO] - Epoch [1/24][1863/3517] loss: 6.95, eta: 9 days, 3:29:56, time: 40.35s, data: 39405ms, mem: 1975M
[2023-09-21 21:38:16,213][INFO] - Epoch [1/24][1864/3517] loss: 7.28, eta: 9 days, 3:29:18, time: 8.95s, data: 28ms, mem: 1975M
[2023-09-21 21:38:20,397][INFO] - Epoch [1/24][1865/3517] loss: 6.77, eta: 9 days, 3:25:11, time: 4.20s, data: 55ms, mem: 1975M
[2023-09-21 21:38:32,302][INFO] - Epoch [1/24][1866/3517] loss: 7.59, eta: 9 days, 3:26:44, time: 11.89s, data: 10876ms, mem: 1975M
[2023-09-21 21:38:38,106][INFO] - Epoch [1/24][1867/3517] loss: 7.00, eta: 9 days, 3:23:49, time: 5.82s, data: 30ms, mem: 1975M
[2023-09-21 21:38:39,009][INFO] - Epoch [1/24][1868/3517] loss: 6.77, eta: 9 days, 3:17:16, time: 0.91s, data: 17ms, mem: 1975M
[2023-09-21 21:38:52,577][INFO] - Epoch [1/24][1869/3517] loss: 7.40, eta: 9 days, 3:20:03, time: 13.56s, data: 16ms, mem: 1975M
[2023-09-21 21:38:58,447][INFO] - Epoch [1/24][1870/3517] loss: 6.81, eta: 9 days, 3:17:10, time: 5.87s, data: 25ms, mem: 1975M

**Comment by zhaoyangwei123** [comment]
> 感谢回复，刚刚解决了～

我也是这个问题，我参考网上将nvcc也调整到了10.2但是还是出现了这个错误，请问你是怎么解决的呢？
