### ISSUE TITLE
Evaluation Error

### ISSUE THREAD

**Issue by smritish21** [MCG-NJU/SparseBEV#48]
Hi, I'm trying to run the evaluation on the code but getting the below error:-

[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 28130/28130, 2.0 task/s, elapsed: 14405s, ETA:     0s
Formating bboxes of pts_bbox
Start to convert detection format...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 28130/28130, 36.3 task/s, elapsed: 775s, ETA:     0ss
Results writes to submission/pts_bbox/results_nusc.json
Evaluating bboxes of pts_bbox
Traceback (most recent call last):                                                                                                                                                               
  File "val.py", line 141, in <module>
    main()
  File "val.py", line 137, in main
    evaluate(val_dataset, results, -1)
  File "val.py", line 20, in evaluate
    metrics = dataset.evaluate(results, jsonfile_prefix='submission')
  File "/netscratch/user/miniforge3/envs/sparsebev_torch_1_9/lib/python3.8/site-packages/mmdet3d/datasets/nuscenes_dataset.py", line 509, in evaluate
    ret_dict = self._evaluate_single(result_files[name])
  File "/netscratch/user/miniforge3/envs/sparsebev_torch_1_9/lib/python3.8/site-packages/mmdet3d/datasets/nuscenes_dataset.py", line 399, in _evaluate_single
    nusc_eval = NuScenesEval(
  File "/netscratch/user/miniforge3/envs/sparsebev_torch_1_9/lib/python3.8/site-packages/nuscenes/eval/detection/evaluate.py", line 84, in __init__
    assert set(self.pred_boxes.sample_tokens) == set(self.gt_boxes.sample_tokens), \
AssertionError: Samples in split doesn't match samples in predictions.
(sparsebev_torch_1_9) user@xxxx:~/SparseBEV$ 

I'm running validation with these options:- 
--config configs/r50_nuimg_704x256.py --weights checkpoints/r50_nuimg_704x256.pth

**Comment by afterthat97** [comment]
The length of validation set is 6019, but in your log it's 28130. You've definitely messed up some code.

**Comment by smritish21** [comment]
I have not made any changes to the code I pulled, can you help me point out what change could alter the length of the validation set?

**Comment by afterthat97** [comment]
28130 is the length of training set. Maybe you used the wrong pkl?

**Comment by smritish21** [comment]
It worked for me, for some debugging I pointed my code to the training pkl file and missed it later. Thanks for the help
